### PR TITLE
Adds cairosvg as SVG preview builder

### PR DESCRIPTION
**Pull request by frague59**
Warning ! Do not merge: no clean...

### CODE REVIEW

**Comment by frague59** [comment]
+ Tests updates: more files

**Comment by frague59** [comment]
Seems clean:
+ svg support with cairosvg, exports JPEG and PDF
+ Adds some tests for various svg files

**Comment by frague59** [comment]
Might be merge-able...

**Comment by frague59** [comment]
OK for docs

**Comment by inkhey** [comment]
@frague59 test are broken due to missing cairosvg in setup.py

**Comment by inkhey** [comment]
@frague59 Test failed because code try to use inkscape builder instead of cairosvg one.

**Comment by lebouquetin** [comment]
@frague59 @inkhey I talked to @liZe (cairosvg author); he confirmed that both inkscape and cairosvg might be usefull because there is no better implementation of SVG (some stuff will be better in inkscape while others will be better in cairosvg)

I suggest... I don't know exactly but we should keep both. I think tests must access directly to builder, not get it from manager.

**Comment by liZe** [comment]
Hey everybody,

Thanks a lot for using CairoSVG!

CairoSVG and Inkscape are very different SVG renderers. Using a simple Python library is probably cleaner than relying on software with a graphical interface, but both have their pros and cons.

You can also take a look at librsvg (GNOME's default SVG renderer). It's widely used and already installed on many Linux desktops. I think that it supports less SVG features than CairoSVG and Inkscape, but I'm obviously not neutral about that :wink:.

Last but not least: during our discussion, I've forgot to say that the most advanced renderers for SVG are browsers. I don't know if it's easy (or even desirable, it's a huge dependency) to use them in preview-generator, but it should be possible.

**Comment by inkhey** [comment]
Hello @frague59 wave
Thank for this feature.
Could you allow us to modify you branch directly to help us release the feature sooner ? (see https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)

**Comment by lebouquetin** [comment]
@frague59 could you send me both your postal address and your tshirt size in order I send you the algoo tshirt ? lets send it to my professionnal email : damien dot accorsi arobase algoo dot fr

**Pull request merged**
