### PR TITLE
Added resampling when previewing a PDF for better quality.

### PR DESCRIPTION
**Pull request by edwardvk**
Addresses issue #71 by adding `resample=True` to `resize()`.

### CODE REVIEW

**Comment by basilelegal** [comment]
@lebouquetin @inkhey It does improve the quality, there is still some noise around letters but the shape of them is consistent.

screenshot at 2019-03-01 10-43-55

Without zoom, it is a lot easier to read and doesn't change the quality of images.
Files have the same size.

screenshot at 2019-03-01 10-48-46
 

Thanks @edwardvk

**Comment by inkhey** [comment]
Thanks @edwardvk for thoses fix,
Can you create another pull request for the file decryption issue fix (see issue #52 ) ?

**Comment by lebouquetin** [comment]
@edwardvk for extra explanation: 

-  we want to merge your code but we prefer to merge it as 2 features (it implements improvment in pdf quality + support for encrypted PDF)
- by the way, the given pdf file for test case seems to be a real PDF file. Is it the case? Is it safe to publicly use it?

**Comment by edwardvk** [comment]
I've closed the re-opened the pull request. (I think it will include the new commit?)

It is a real PDF. I was unable to create a non-worked PDF myself, so I used a real one. It does not contain any interesting information. You can make it public.

**Comment by inkhey** [comment]
@edwardvk We move theses fix in 2 other MR : 
- https://github.com/algoo/preview-generator/pull/75 - for resampling
- https://github.com/algoo/preview-generator/pull/76 - for decryption fix.

**Pull request closed without merging**
