### PR TITLE
add cad__vtk builder for STL files

### PR DESCRIPTION
**Pull request by Zepmanbc**
PyconFR2019

### CODE REVIEW

**Comment by inkhey** [comment]
Hello @Zepmanbc :wave: 
Thank for this feature.
Could you allow us to modify you branch directly to help us release the feature sooner ? (see https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)

**Comment by Zepmanbc** [comment]
Hi @inkhey 
it's done

**Comment by inkhey** [comment]
> Hi @inkhey
> it's done

Doesn't seems to work. Don't really know why.

**Comment by Zepmanbc** [comment]
@inkhey  and now?

**Comment by inkhey** [comment]
> @inkhey and now?

It's ok. code now merged

**Comment by lebouquetin** [comment]
@Zepmanbc could you send me both your postal address and your tshirt size in order I send you the algoo tshirt ? lets send it to my professionnal email : damien dot accorsi arobase algoo dot fr

**Pull request merged**
