### PR TITLE
Fix: 293

### PR DESCRIPTION
**Pull request by a523**
https://github.com/algoo/preview-generator/issues/293
## PR Goal
fix bug  https://github.com/algoo/preview-generator/issues/293 

## Checkpoints

- [x] If relevant, **manual tests** have been done to ensure the stability of the whole application and that the involved feature works
- [x] **Automated tests** covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)
- [x] The PR or the original issue contains a **short summary of the implemented solution**.

### CODE REVIEW

**Comment by a523** [comment]
@inkhey  Please take a look

**Comment by inkhey** [comment]
@a523 Thanks for this contribution.
Just for information, before the introduction of the auto-rotate you introduced during switching to pillow, we consider an other way to do so by copying exif information : https://github.com/algoo/preview-generator/issues/166. This seems a bit more complicated, so i will check and validate your PR to have a consistent behavior for now, but we may decide to change this a bit later. I personally don't have strong opinion which solution is better.

**Comment by inkhey** [comment]
Properly tested, and fixed mypy issue on branch ci_test/fix293. Can you merge it in your branch, so i can merge this PR ?

to avoid such mypy in CI, you can do :
` mypy --ignore-missing-imports --disallow-untyped-defs .`
before suggesting PR.

The problem seems that pre-commit config (https://github.com/algoo/preview-generator/blob/develop/.pre-commit-config.yaml) does not contain mypy whereas CI check it (https://github.com/algoo/preview-generator/blob/develop/concourse/scripts/lint).

**Comment by a523** [comment]
1. certainly, I have merged.
2. I'm sorry, I did forgot to run mypy checks, will pay attention next time.
@inkhey

**Comment by inkhey** [comment]
@a523  You're welcome. Thanks ;-)

**Pull request merged**
