### PR TITLE
Add support for GLTF export

### PR DESCRIPTION
**Pull request by cromize**
This PR:
1. Fixes import issue for 3D vtk readers (newer version of vtk changed naming). I would consider freezing packages version.
2. Adds support for vtk GLTF reader.

### CODE REVIEW

**Review by inkhey — CHANGES_REQUESTED** [review]
Hello, thanks for your contribution.
As this PR make the code compatible vtk9 as far i understood, we should probably now be able to be fully 3.8 compatible.
Can you:
- add a test for GLTF file ? (see stl example)
- change the required vtk to vtk>=9 in setup.py and remove the xfail mark in stl test in order to test if vtk does work correctly now on python 3.8.

As soon as tests for both stl and gltf passed on travis on all python version, i do think we should be able to merge this (and probably release a new version of Preview Generator soon).

**Comment by cromize** [comment]
I added test for gltf. Gltf test is passing for python >= 3.6. It's failing on 3.5 because pypi is missing vtk9 package for linux.

Travis seems to have problem getting vtk9 package from pypi on python3.8. I tried to trigger travis build couples times, but I had to pip install vtk manually to make it work. 

It worked locally though when I tried it on same ubuntu vm.

**Comment by inkhey** [comment]
Thanks for you changes.

> I added test for gltf. Gltf test is passing for python >= 3.6. It's failing on 3.5 because pypi is missing vtk9 package for linux (linux is only missing platform).

As far i see tests, most vtk features does work with new code on python 3.5, can you confirm that ?
If i'm correct, i suggest to:
- explicitly disable GLTF support for python 3.5.
- explictly install vtk > 9 for python 3.6+ and the last working version for 3.5 in setup.py.

One other way will be dropping python 3.5 support but we do need to support it a bit longer.

> 
> Travis seems to have problem getting vtk9 package from pypi on python3.8. I tried to trigger travis build couples times, but I had to pip install vtk manually to make it work.
> 
> It worked locally though when I tried it on same ubuntu vm.

Curious. I don't think it's a big issue. just comment this where you force the install.

**Comment by inkhey** [comment]
@cromize , This PR as been replaced by https://github.com/algoo/preview-generator/pull/195.
It should be straightforward to merge it now. Just need to verify all is ok.
We will merge this by squashing commits and keep you as co-contributor.

**Pull request closed without merging**
